### ISSUE TITLE
get the live plot with openscope using python i was able to get 1 (sec) data with 10 sec delay

### ISSUE THREAD

**Issue by jotheshjolly** [davidbradway/pyopenscope#2]
i need to plot the data like waveforms live using python and i got partially but the data which i get the delay of some 10 sec for 1 sec data and thats huge delay i need to figure it out 
As i am using this code https://github.com/ravikumargrk/PyOpenScope

I will appreciate your help with this situation.

**Comment by davidbradway** [comment]
If you are using that code, try filing an Issue at https://github.com/ravikumargrk/PyOpenScope/issues
I haven't touched this in a long time. I might not be much help.
